### ISSUE TITLE
`taxize` is offline

### ISSUE THREAD

**Issue by diazrenata** [role-model/multidim-biodiv-data#119]
See https://github.com/ropensci/taxize/issues/915; the GNR resource seems to have been taken offline leading to failures of `taxize::gnr_resolve`. 

I suggest cutting the `taxize` sections.

**Comment by diazrenata** [comment]
Possibly switch to TRNS in rotl? https://cran.r-project.org/web/packages/rotl/vignettes/rotl.html

**Comment by diazrenata** [comment]
from @isaacovercast https://github.com/gnames/gnverifier

**Comment by diazrenata** [comment]
:eyes: https://mctavishlab.github.io/R_OpenTree_tutorials/01-find-taxa/index.html

**Comment by bryanpgalligan** [comment]
Is there a plan to update taxize and bring it back online?
