### ISSUE TITLE
Evaluating code with loaded packages in .Rmd episodes breaks build

### ISSUE THREAD

**Issue by diazrenata** [role-model/multidim-biodiv-data#14]
See https://github.com/role-model/multidim-biodiv-data/commit/fe77fca231afd16a7687f09a81fa656a552e2f17

This lesson has packages loaded (dplyr, ggplot2, hillR) and this seems to cause the site build to get stuck updating the package cache (see build logs). 

Interestingly this is occurring even when the _entire text of the lesson is commented out_, at least according to .Rmd (`<!-- -->` fences). It seems to work ok if all the .Rmd chunks are set to not evaluate (` ```{r eval = F}`).

**Comment by diazrenata** [comment]
this is kind of inconvenient because it leads to doing the lesson code dev separate from the final lesson .Rmd :shrug:

**Comment by connor-french** [comment]
Fixed with a173210. Should also let the carpentries devs know about this.
