### ISSUE TITLE
abundance module edits

### ISSUE THREAD

**Issue by diazrenata** [role-model/multidim-biodiv-data#26]
- [ ] update questions to include data wrangling
- [ ] decide whether learners have all the packages installed ahead.
- [ ] either way, checkpoint after package loads to make sure everyone has it.
- [x] tinyurl, bit.ly for data path
- [x] context on gnr_resolve - trade off instructors
- [x] update Agrotis to Peridroma chersotoides
- [ ] decide how many and which approaches for aggregrate/summarize:
     - see how folks do with groupsumungroup
     - hide aggregate and try it if needed
     - learn from this
- [ ] introduce par earlier? to look at sads side by side. and overlaid.
- [ ] site by species matrix (pivot_wider)
- [ ] switch to hillR - bug is fixed
- [ ] calculate exponential of shannon's
- [ ] add subplot panel titles
- [ ] save abundance data as .csv

**Comment by connor-french** [comment]
Quick note on `summarize`- `summarize` already removes grouping, so it's unnecessary to run `ungroup` after running summarize. Might drop the cognitive load and not leave them hanging. You'd have to run `ungroup` if you ran `mutate` rather than `summarize`
