### ISSUE TITLE
Post-workshop Survey

### ISSUE THREAD

**Issue by Rilquer** [role-model/multidim-biodiv-data#55]

**Comment by diazrenata** [comment]
Carpentries has archives that are a good example, but not specific to our workshop. I believe these are CC, but I would want to check further before using anything copy-paste:
https://carpentries.github.io/assessment-archives/

https://carpentries.github.io/assessment-archives/pre-workshop/pre-workshop.html

https://carpentries.github.io/assessment-archives/post-workshop/post-workshop.html
