### ISSUE TITLE
Are we interested in adding “Challenges” separate from “Exercises”?

### ISSUE THREAD

**Issue by Rilquer** [role-model/multidim-biodiv-data#63]
Are we interested in adding “Challenges” separate from “Exercises” that won’t be covered step by step in class but can be done by more experienced R users to keep them engaged?

**Comment by diazrenata** [comment]
https://carpentries.github.io/sandpaper-docs/episodes.html#callout-blocks

This explains some of the 

```
::: challenge

::: solution

:::

:::

``` 

syntax folks have been using, but we've had a lot of errors with it. 

Best way forward? :shrug: It'd be sweet to use :::challenge if we can.
