### ISSUE TITLE
create outline on finding mult-dim biodiversity data

### ISSUE THREAD

**Issue by ajrominger** [role-model/multidim-biodiv-data#74]
notes:

```
## Finding multi-dimensional data


::: questions

- Where do multi-dimensional biodiversity data live online?
- How can we combine online resources to assemble multi-dimensional datasets?
- How can we use R to retrieve data?

:::::::::::::


::: objectives

After following this episode, we intend that participants will be able to:

1. List online repositories (kinda lame)
1. Retrieve data from xyz (insert repo names here, e.g. GEOME) using R and APIs
1. Assemble a synthetic data set of multiple dimensions of biodiversity from multiple online sources

::::::::::::::

### NOTES

- do we talk about metadata standards here? or under each data type episode? or in next episode contributing data????
```

**Comment by diazrenata** [comment]
- which data bases
- which datasets?
    - c.f. suggests mammals 🐭  🐘  ✨ 
- do we want to work through a full example of finding many/all types and connecting them? is this feasible? is this what folks would realistically encounter in the wild?

**Comment by diazrenata** [comment]
jacob thoughts, rmd notes:

* on finding data: is it helpful to teach paper scraping skills/lit review/big databases?
        * section on tools and tricks for getting data out of published papers
* larger databases
        * emphasize using APIs
        * note that APIs can be constrained by file size
        * or request limit
        * ^^ the above, good things to know about when using APIs

**Comment by diazrenata** [comment]
* include section on metadata standards

**Comment by diazrenata** [comment]
what even are multidimensional databases?

- neon
- edi has some
- encyclopedia of life?

to cover:
- gbif, ncbi

**Comment by diazrenata** [comment]
Everyone think about repositories!
