### ISSUE TITLE
do we assume aligned seqs or raw seqs in pop gen episode?

### ISSUE THREAD

**Issue by ajrominger** [role-model/multidim-biodiv-data#93]

**Comment by connor-french** [comment]
I think raw seqs are fine, as long as we have enough time to talk about this section. Also, we need to decide whether sequence data will be simulated and "unaligned" or if we use real sequence data or another option. Regardless, here's an example workflow once we have raw sequence data:

```
library(msa)

mySequenceFile <- "/Users/connorfrench/Dropbox/Old_Mac/School_Stuff/CUNY/Courses/Spring-2019/Machine-Learning/project/fasta/hypsiboas_seqs_aligned.fas"
mySequences <- readDNAStringSet(mySequenceFile)
mySequences

myFirstAlignment <- msa(mySequences)

ape_align <- msaConvert(myFirstAlignment, type = "ape::DNAbin")

ape::write.FASTA(ape_align, "~/Downloads/trial_fasta.fas")
```

I'm going to open a separate issue for actually incorporating this into the episode.

**Comment by connor-french** [comment]
Closing this- I'm going to add the section and we can cut if needed
