### ISSUE TITLE
how to bring metabarcoding data into the pop gen episode

### ISSUE THREAD

**Issue by ajrominger** [role-model/multidim-biodiv-data#94]
have a look at this for more on ASVs: https://benjjneb.github.io/dada2/tutorial.html

**Comment by connor-french** [comment]
Idea: Keep the VCF section as an "additional information" section, but replace it in the workshop with a section on ASVs and metabarcoding. I think it's appropriate to place it after the FASTA section.
For the ASV section, proposed structure:
## ASVs and Metabarcoding
overview
### FASTQ
brief overview/comparison with FASTA
### DADA2
Briefly go over the steps for processing, but let them know we are concerned with processing the output for biodiversity analysis and refer them to the documentation
### Metabarcoding table
Go over metabarcoding table structure and provide our example data
### Hill numbers
Calculate hill numbers, plot, etc.

**Comment by connor-french** [comment]
paper for reference: https://www-nature-com.ezproxy.gc.cuny.edu/articles/ismej2017119

**Comment by connor-french** [comment]
we have a solid draft
